# -*- coding: utf-8 -*-
"""copia de gym laura .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tYnuLXdVjHOQuTl2YVGjIjRoKZ2jRhqX
"""

link = "https://raw.githubusercontent.com/casaorozco1904-ship-it/Estadistica2026/refs/heads/main/gym_members_exercise_tracking%20(1).csv"

import pandas as pd

df = pd.read_csv(link)

df

df.info()

df.describe()

#test de tukey
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import matplotlib.pyplot as plt

nivel_de_significancia = 0.05

# Prueba de Tukey
tukey = pairwise_tukeyhsd(endog=df['calorias_quemadas'], groups=df['genero'], alpha=nivel_de_significancia)

# Mostrar los resultados
print(tukey)

# Gráfico de las diferencias entre grupos
tukey.plot_simultaneous(ylabel="Grupos", xlabel="Medias")

plt.gca().spines['right'].set_visible(False) # derecha
plt.gca().spines['top'].set_visible(False)   # superior
plt.title("Múltiples comparaciones entre todos los pares (Tukey)")

df["genero"]=df["genero"].map({"Female":0,"Male":1})

df

#test de tukey
from statsmodels.stats.multicomp import pairwise_tukeyhsd
import matplotlib.pyplot as plt

nivel_de_significancia = 0.05

# Prueba de Tukey
tukey = pairwise_tukeyhsd(endog=df['calorias_quemadas'], groups=df['tipo_entrenamiento'], alpha=nivel_de_significancia)

# Mostrar los resultados
print(tukey)

# Gráfico de las diferencias entre grupos
tukey.plot_simultaneous(ylabel="Grupos", xlabel="Medias")

plt.gca().spines['right'].set_visible(False) # derecha
plt.gca().spines['top'].set_visible(False)   # superior
plt.title("Múltiples comparaciones entre todos los pares (Tukey)")

df["tipo_entrenamiento"]=df["tipo_entrenamiento"].map({"Cardio":0,"Yoga":1,"Strength":2,"HIIT":3})

df

#Mapa de calor

import seaborn as sns
import matplotlib.pyplot as plt

correlation_matrix = df.corr()
plt.figure(figsize=(30, 18))
sns.heatmap(correlation_matrix,
            annot=True,
            cmap='coolwarm',
            fmt=".4f",
            square=True,
            center=0,
            cbar_kws={"shrink": .8})
plt.title('Mapa de Calor de la Matriz de Correlación')
plt.show()

df=df[["duracion","nivel experiencia","frecuencia_entrenamiento","genero","edad","calorias_quemadas"]]

#Mapa de calor

import seaborn as sns
import matplotlib.pyplot as plt

correlation_matrix = df.corr()
plt.figure(figsize=(30, 18))
sns.heatmap(correlation_matrix,
            annot=True,
            cmap='coolwarm',
            fmt=".4f",
            square=True,
            center=0,
            cbar_kws={"shrink": .8})
plt.title('Mapa de Calor de la Matriz de Correlación')
plt.show()

x=df[["duracion","frecuencia_entrenamiento","genero","edad"]]
y=df["calorias_quemadas"]

import statsmodels.api as sm
x_constante=sm.add_constant(x)
modelo=sm.OLS(y,x_constante).fit()
y_calculada=modelo.predict(x_constante)
modelo.params

modelo.predict([1,20000,0,1,50])

# @title
# 2. Realice un diagrama de dispersión para estos datos.
import matplotlib.pyplot as plt

# --- Configuración general del gráfico ---
plt.figure(
    figsize=(6, 4),   # tamaño de la figura (ancho, alto) en pulgadas
    dpi=120           # resolución del gráfico
)

# --- Gráfico de dispersión ---
plt.scatter(
    y, y_calculada,
    marker="o",       # forma
    color='blue',     # color de los puntos
    edgecolor='Blue',    # borde de los puntos
    alpha=0.1,            # transparencia
    s=50,                 # tamaño de los puntos
    label='calorias_reales' # etiqueta para la leyenda
)

# --- Gráfico de línea ---
plt.plot(
    y_calculada, y_calculada,
    color='black',   # color de la línea
    linewidth=1,        # grosor de la línea
    linestyle='--',        # estilo de línea
    marker='o',           # marcador en cada punto
    markersize=0,         # tamaño del marcador
    markerfacecolor='white',
    markeredgecolor='black',
    label='Recta de regresión'
)

# --- Título ---
plt.title(
    '''Gráfico de dispersión entre
    calorias reales  y calorias hipoteticas''',
    fontsize=14,
    fontweight='bold'
)

# --- Etiquetas de los ejes ---
plt.xlabel(
    'calorias reales',
    fontsize=12
)

plt.ylabel(
    'calorias hipoteticas',
    fontsize=12
)

# --- Fuente de los ticks ---
plt.xticks(fontsize=10)
plt.yticks(fontsize=10)

# --- Márgenes ---
plt.margins(x=0.05, y=0.05)  # espacio extra alrededor de los datos
plt.gca().spines['right'].set_visible(False) # derecha
plt.gca().spines['top'].set_visible(False)   # superior

# Para eliminar márgenes completamente, usar:
# plt.margins(0)

# --- Cuadrícula (opcional, pero didáctica) ---
plt.grid(
    visible=True,
    linestyle='--',
    linewidth=0.7,
    alpha=0.1,
    color="gray"
)

# --- Leyenda ---
plt.legend(
    fontsize=10,
    loc='best',
    frameon=True
)

# --- Nota al pie ---
plt.text(
    0.4, -0.2,
    'Fuente: datos simulados para fines académicos.',
    fontsize=8,
    ha='left',
    va='center',
    transform=plt.gca().transAxes
)

# --- Guardar gráfico ---
plt.savefig(
    "grafico de dispersión",
    bbox_inches='tight'
    )

plt.show()

# 5. Calcule el coeficiente de determinación e interprete el resultado.
from sklearn.metrics import r2_score  # recomendada
r2 = r2_score(y, y_calculada)
print(f'Coeficiente de determinación: {r2: 0.2%}\n')

# 7. Obtenga un intervalo de confianza del 95% para la pendiente de la recta de
# regresión ajustada ( b1 )

# intervalo de confianza = 1 - alpha

modelo.conf_int(alpha = 0.05)

# 8. Calcule los residuales y trace un nuevo gráfico de dispersión. Comente,
# ¿Parece que se verifican los supuestos?

# Los residuales son la diferencia entre el valor real y el valor que da el
# modelo

# residuales = y - y_calculada
residuales = modelo.resid

residuales

# 9. Realice la prueba de Shapiro para los residuales y comente el resultado.

# Test de Shapiro-Wilk
# H0: Hay normalidad
# H1: No hay normalidad
# alpha = 0.05

from scipy.stats import shapiro
residuales=modelo.resid
from scipy.stats import shapiro
import matplotlib.pyplot as plt
import seaborn as sns

# Prueba de Shapiro-Wilk
stat, valor_p_sh = shapiro(residuales)
print(f"valor-p (Shapiro) = {valor_p_sh}")

# Visualización: Q-Q plot
sm.qqplot(residuales, line='s')
plt.title("Q-Q plot de residuos")
plt.show()

# Histograma
sns.histplot(residuales, kde=True)
plt.title("Histograma de residuos")
plt.show()

# 10. Realice la prueba de Breusch-Pagan para los residuales
# y comente el resultado.

# Test de Breusch-Pagan
# H0: No hay heterocedasticidad (dispersión es igual en toda la recta)
# H1: Hay Heterocedasticidad (dispersión distinta a lo largo de la recta)
# alpha = 0.05

from statsmodels.stats.api import het_breuschpagan
_, valor_p_bp, _, _ = het_breuschpagan(residuales, x_constante)
print(f'valor_p de Breusch-Pagan: {valor_p_bp: 0.4f}\n')

# 12. Realice una tabla ANOVA e interprete el resultado.

# test de ANOVA (Analysis of Variance)
# H0: beta_1 = 0   (No hay correlación)
# H1: beta_1 ≠ 0   (Sí hay correlación)

from statsmodels.formula.api import ols
# Y ~ X
modelo_lineal = ols(' calorias_quemadas~duracion+frecuencia_entrenamiento+genero+edad	', data = df).fit()
tabla_anova = sm.stats.anova_lm(modelo_lineal)
tabla_anova





























































